# Font
font_family      postscript_name=DankMono-Regular
bold_font        postscript_name=DankMono-Bold
italic_font      postscript_name=DankMono-Italic
bold_italic_font auto
font_size        16.0

# Cursor
cursor_shape            block
cursor_shape_unfocused  hollow
cursor_beam_thickness   1.5
cursor_blink_interval   0

# Window
background_opacity   0.80
background_blur      30
macos_titlebar_color background

# macOS
macos_option_as_alt left

# Keys
map cmd+right next_tab
map cmd+left  previous_tab
map cmd+t     new_tab
map cmd+w     close_tab

# Bell
enable_audio_bell    no
visual_bell_duration 0.15
window_alert_on_bell yes
